name: Weeder
description: Annotate unused functions in a Haskell project
inputs:
  working-directory:
    description: Change to this directory before operating
    required: true
    default: .
  weeder-version:
    description: Version of weeder to install (default 2.4.0)
    required: true
    default: "2.4.0"
  weeder-arguments:
    description: |
      Arguments to pass when invoking weeder (default --require-hs-files)
    required: true
    default: --require-hs-files
  fail:
    description: Fail the build if unused functions found? (default true)
    required: true
    default: true
outputs:
  log:
    description: Path to file containing the output from weeder
    value: ${{ steps.weeder.outputs.log }}
runs:
  using: composite
  steps:
    - name: Install weeder
      uses: pbrisbin/setup-tool-action
      with:
        name: weeder
        version: ${{ inputs.weeder-version }}
        url: "https://github.com/freckle/weeder-action/releases/download/Binaries/{name}-{version}-{arch}-{os}.{ext}"

    - id: weeder
      name: Run weeder
      shell: bash
      run: |
        echo "::add-matcher::${{ github.action_path }}/matcher.json"
        trap 'echo "::remove-matcher owner=freckle-weeder::"' EXIT

        tmp=$(mktemp)
        echo "log=$tmp" >>"$GITHUB_OUTPUT"

        cd '${{ inputs.working-directory }}'
        prefix=$(echo '${{ inputs.working-directory }}' | sed 's|/$||')/
        weeder ${{ inputs.weeder-arguments }} |
          sed "s|^|$prefix|; "'s/$/ is not used by any defined root/' |
          tee "$tmp" || true

        if ${{ inputs.fail }} && [[ -s "$tmp" ]]; then
          echo "Configured to fail and unused functions found"
          exit 1
        fi
